service: api-viva
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  environment:
    bucketName: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

  uploader:
    handler: lambdas/getFile.handler
    events:
      - httpApi:
          path: /upload
          method: post

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}

plugins:
  - serverless-s3-sync
  - serverless-webpack

package:
  individually: true

custom:
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: UploadData
  bucketName: vivaaerobucket123123
